version: '3.8'

services:
  emr:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    ports:
      - "80:80"
    environment:
      - PATIENT_COUNT=25              # Number of patients to generate
      - SKIP_SYNTHEA=false           # Set to true to skip patient generation
      - SKIP_IMPORT=false            # Set to true to skip data import
    volumes:
      - emr_data:/app/backend/data    # Persist database between restarts
      - emr_logs:/app/backend/logs    # Persist logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  emr_data:
    driver: local
  emr_logs:
    driver: local