version: '3.8'

services:
  backend:
    build: ./backend
    container_name: emr-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/emr.db
      - SECRET_KEY=training-environment-key
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=8
      - CORS_ORIGINS=*
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: emr-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000

  data-init:
    build: ./backend
    container_name: emr-data-init
    command: python scripts/optimized_comprehensive_setup.py --quick --skip-synthea
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - backend
    profiles:
      - setup