version: '3.8'

services:
  # Frontend builder service
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    container_name: emr-frontend-builder
    volumes:
      - ./frontend/build:/build
    networks:
      - emr-network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.production.complete
    container_name: emr-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - emr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - frontend-builder

  nginx:
    image: nginx:alpine
    container_name: emr-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-builder
    networks:
      - emr-network

networks:
  emr-network:
    driver: bridge
