version: '3.8'

services:
  # All-in-one container with backend, frontend, nginx, and Synthea
  emr:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
    container_name: emr-all-in-one
    ports:
      - "80:80"        # Main application
      - "8000:8000"    # API (optional, for direct access)
    environment:
      - PATIENT_COUNT=${PATIENT_COUNT:-50}  # Number of Synthea patients to generate
    volumes:
      - ./data:/app/data                    # Persist database
      - ./logs:/app/logs                    # Persist logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Give time for Synthea to run

volumes:
  emr-data:
  emr-logs: