version: '3.8'

services:
  backend:
    build: ./backend
    container_name: emr-backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/emr.db}
      - SECRET_KEY=${SECRET_KEY:-development-secret-key-change-in-production}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=8
      - CORS_ORIGINS=http://localhost,http://localhost:3000,http://localhost:80
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    networks:
      - emr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: emr-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - emr-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  emr-network:
    driver: bridge

volumes:
  emr-data:
  emr-logs: